-- Seed 5 AI-generated perspectives for each article
-- Runs with superuser privileges (bypasses RLS)

UPDATE public.articles SET perspectives = '[
  {"id":"economica","label":"Económica","icon":"📈","tone":"Analítico","content":["Las exportaciones brasileñas de soja y commodities agrícolas alcanzaron un récord histórico, impulsadas por la demanda china y la depreciación del real frente al dólar.","El superávit comercial fortalece las reservas del Banco Central do Brasil, dando margen para la política monetaria en un contexto de inflación moderada.","La concentración en commodities expone estructuralmente a Brasil a la volatilidad de precios internacionales, señalado como el talón de Aquiles del modelo exportador."]},
  {"id":"politica","label":"Política","icon":"🏛️","tone":"Contextual","content":["El gobierno de Lula utiliza el récord exportador para defender su política de reindustrialización, tensando la relación con el agronegocio que demanda menor intervención estatal.","La disputa por ingresos del comercio exterior refleja la fractura interna: norte industrial versus agronegocio del centro-oeste.","En política exterior, Brasil aprovecha su posición para ganar influencia en el G20 y relanzar las negociaciones del acuerdo Mercosur-Unión Europea."]},
  {"id":"social","label":"Social","icon":"👥","tone":"Humano","content":["El boom exportador no alcanza a los trabajadores rurales del nordeste, donde la pobreza persiste a pesar de los números positivos. La riqueza se concentra geográficamente.","Comunidades indígenas y quilombolas denuncian que la expansión agrícola avanza sobre sus territorios, ignorando derechos constitucionales.","En ciudades portuarias como Santos, el crecimiento logístico generó empleos pero también contaminación que degrada la calidad de vida local."]},
  {"id":"internacional","label":"Internacional","icon":"🌍","tone":"Geopolítico","content":["China consolida su posición como principal destino de exportaciones brasileñas, superando a EE.UU. Esta dependencia preocupa a Washington.","La guerra comercial sino-estadounidense abre oportunidades para Brasil como proveedor alternativo en mercados que buscan desconcentrar cadenas de suministro.","La UE condiciona el acuerdo Mercosur al cumplimiento de estándares ambientales, generando tensión con el agronegocio brasileño."]},
  {"id":"cultural","label":"Cultural","icon":"🎭","tone":"Reflexivo","content":["Brasil exporta soja pero también cultura: series globales, música pop y arquitectura. La identidad exportadora del país es más amplia que sus estadísticas comerciales.","El orgullo por el récord convive con una pregunta identitaria: ¿es Brasil un país de recursos naturales o de ideas?","La gastronomía brasileña gana espacio mundial como vector de soft power, recordando que no toda exportación valiosa se mide en toneladas."]}
]'::jsonb
WHERE id = 'c513d0c8-82d3-4ef4-a86e-3da8ef396462';

UPDATE public.articles SET perspectives = '[
  {"id":"economica","label":"Económica","icon":"📈","tone":"Analítico","content":["La inversión pública en tecnología educativa en Chile alcanzó un récord, posicionando al país como el mayor inversor per cápita en edtech de América Latina.","Expertos cuestionan el retorno de inversión: la tecnología sin formación docente adecuada no mejora resultados académicos medibles según estudios de la OCDE.","El mercado privado de edtech creció un 35% interanual, atrayendo capital de riesgo regional que ve en la reforma una oportunidad de largo plazo."]},
  {"id":"politica","label":"Política","icon":"🏛️","tone":"Contextual","content":["El gobierno de Boric impulsó la reforma como parte de su agenda de modernización, pero enfrenta resistencia de sindicatos docentes que temen la desprofesionalización.","La oposición apoya la incorporación tecnológica pero critica el rol del Estado como comprador exclusivo, argumentando que limita la innovación privada.","La reforma coincide con el proceso constituyente fallido, en un clima donde cualquier cambio estructural en educación despierta sensibilidades históricas."]},
  {"id":"social","label":"Social","icon":"👥","tone":"Humano","content":["En comunas rurales de La Araucanía, la brecha digital hace que la reforma llegue como promesa pero no como realidad: sin internet de calidad, las tablets son ornamentos.","Docentes en zonas vulnerables reportan que los dispositivos reemplazan tiempo de vínculo con los alumnos, generando paradojas pedagógicas que los datos no capturan.","Estudiantes de colegios municipales acceden por primera vez a herramientas de programación e IA, abriendo horizontes antes reservados a establecimientos privados."]},
  {"id":"internacional","label":"Internacional","icon":"🌍","tone":"Geopolítico","content":["Chile se convierte en laboratorio regional de políticas edtech, atrayendo atención del BID y la UNESCO que buscan modelos replicables para la región.","La reforma incorpora plataformas de empresas globales, generando debate sobre soberanía de datos educativos y dependencia de proveedores extranjeros.","Finlandia y Estonia asesoran el proceso chileno pero advierten que sus modelos requieren décadas de construcción institucional para funcionar."]},
  {"id":"cultural","label":"Cultural","icon":"🎭","tone":"Reflexivo","content":["La pregunta de fondo no es tecnológica sino cultural: ¿qué ciudadano quiere formar Chile? La tecnología amplifica el modelo pedagógico existente, no lo transforma sola.","La resistencia docente tiene raíces en una identidad profesional construida alrededor del vínculo humano. Introducir algoritmos toca fibras identitarias profundas.","La generación que aprende con IA hoy será la que defina el Chile del 2040. La reforma es una apuesta sobre qué valores serán valiosos en ese futuro."]}
]'::jsonb
WHERE id = 'db6822a1-9a06-46ec-b321-6ce79823eb54';

UPDATE public.articles SET perspectives = '[
  {"id":"economica","label":"Económica","icon":"📈","tone":"Analítico","content":["Las startups fintech argentinas procesaron más de $8.000 millones en pagos digitales en el último año, posicionando al país como segundo mercado fintech regional tras Brasil.","En un contexto de alta inflación y restricciones cambiarias, las billeteras virtuales y stablecoins se convirtieron en instrumentos de cobertura para millones de argentinos.","El sector atrajo $320 millones en inversión de venture capital en 2025, récord a pesar de la inestabilidad macro, evidenciando confianza en el potencial del mercado local."]},
  {"id":"politica","label":"Política","icon":"🏛️","tone":"Contextual","content":["El gobierno de Milei desreguló el sector fintech como parte de su agenda libertaria, eliminando restricciones que las startups señalaban como obstáculos para la innovación.","El Banco Central resistió inicialmente la expansión de billeteras virtuales por temores de pérdida de control monetario, generando tensión con el ejecutivo.","La regulación de criptomonedas sigue siendo un limbo legal que startups como Lemon y Ripio navegan con incertidumbre, esperando un marco jurídico claro."]},
  {"id":"social","label":"Social","icon":"👥","tone":"Humano","content":["El 40% de los usuarios de billeteras virtuales en Argentina las usa como sustituto bancario, revelando que el fintech llega donde los bancos nunca llegaron.","En el conurbano bonaerense, feriantes y pequeños comerciantes adoptaron el código QR como método de pago principal, saltando directamente a los pagos digitales.","Las mujeres lideran la adopción de herramientas de ahorro digital, usando stablecoins como escudo frente a la erosión inflacionaria de sus ingresos."]},
  {"id":"internacional","label":"Internacional","icon":"🌍","tone":"Geopolítico","content":["Argentina exporta talento fintech: equipos de ingeniería desarrollan productos para startups de Brasil, México, España y EE.UU., generando divisas en un sector no tradicional.","Inversores de Silicon Valley y Miami ven el ecosistema argentino como cantera de talento barato y altamente capacitado, replicando el modelo de outsourcing tecnológico.","La adopción masiva de criptomonedas en Argentina es observada globalmente como caso de estudio sobre el dinero digital en economías con monedas débiles."]},
  {"id":"cultural","label":"Cultural","icon":"🎭","tone":"Reflexivo","content":["La creatividad financiera argentina nació de la necesidad: décadas de crisis forzaron a los argentinos a desarrollar una inteligencia financiera informal única en el mundo.","El cepo cambiario y el blue dollar crearon una cultura de arbitraje cotidiano que el fintech formalizó y digitalizó. El ingenio para sobrevivir la economía ahora es ventaja competitiva.","Las generaciones jóvenes en Argentina no conciben la relación con el dinero a través de bancos físicos. La billetera virtual es tan natural como el efectivo lo fue para sus padres."]}
]'::jsonb
WHERE id = '15591a28-abd9-44f4-a5c5-d82aa027f71d';

UPDATE public.articles SET perspectives = '[
  {"id":"economica","label":"Económica","icon":"📈","tone":"Analítico","content":["Las elecciones intermedias en México se dan en un contexto de desaceleración económica: el PIB creció apenas un 1.2%, muy por debajo de las expectativas del gobierno entrante.","El peso mexicano se mantiene estable gracias a las remesas récord que superaron los $60.000 millones anuales, convirtiendo a las familias migrantes en el mayor sostén macro del país.","Las promesas de campaña implican aumentos del gasto público de hasta 3 puntos del PIB, lo que analistas advierten podría presionar el déficit fiscal y la calificación crediticia del país."]},
  {"id":"politica","label":"Política","icon":"🏛️","tone":"Contextual","content":["La carrera reñida refleja una polarización profunda entre el bloque continuista del oficialismo y una oposición fragmentada que busca articularse alrededor de candidatos testimoniales.","El sistema electoral mexicano, reformado recientemente, enfrenta su primera prueba real bajo nuevas reglas de financiamiento y veda a organismos autónomos que antes fiscalizaban el proceso.","La popularidad presidencial, que supera el 65%, no se traslada automáticamente a los candidatos del partido, generando tensiones internas que la dirigencia prefiere no ventilar públicamente."]},
  {"id":"social","label":"Social","icon":"👥","tone":"Humano","content":["En comunidades del sur de México, la participación electoral se ve amenazada por la violencia del crimen organizado que controla territorios enteros e impone candidatos propios.","Las mujeres representan el 48% del padrón electoral pero siguen siendo minoría en las listas partidarias, evidenciando la brecha entre paridad formal y participación real en el poder.","Los jóvenes de 18 a 29 años muestran la menor intención de voto de la historia reciente, desencantados de una política que perciben alejada de sus preocupaciones: empleo, vivienda y seguridad."]},
  {"id":"internacional","label":"Internacional","icon":"🌍","tone":"Geopolítico","content":["Washington sigue de cerca las elecciones mexicanas: el resultado definirá la renegociación del T-MEC en 2026 y la cooperación en seguridad fronteriza que EE.UU. considera prioritaria.","China aumentó su presencia económica en México usando al país como plataforma de acceso al mercado norteamericano, lo que genera tensión con la política industrial estadounidense.","El resultado electoral impactará directamente en la política migratoria: un gobierno más conciliador con EE.UU. podría facilitar acuerdos de contención que afectan a migrantes centroamericanos."]},
  {"id":"cultural","label":"Cultural","icon":"🎭","tone":"Reflexivo","content":["Las elecciones mexicanas no son solo una disputa por el poder sino un referendum sobre el proyecto de nación: ¿continuismo transformador o corrección de ruta hacia el pragmatismo?","La cultura política del acarreo y el clientelismo persiste en zonas rurales, revelando que la democracia formal y la democracia real siguen siendo dos experiencias distintas según el código postal.","El humor político mexicano —memes, caricaturas, satiristas— es el termómetro más preciso del humor social. Lo que se ríe en las redes dice más sobre el momento político que cualquier encuesta."]}
]'::jsonb
WHERE id = 'f2145e04-34e2-4b38-88c0-ca3ad8cb8d48';

UPDATE public.articles SET perspectives = '[
  {"id":"economica","label":"Económica","icon":"📈","tone":"Analítico","content":["Las herramientas de IA generativa permiten a las redacciones reducir hasta un 40% el tiempo de producción de contenidos rutinarios, liberando a los periodistas para tareas de mayor valor agregado.","El mercado de soluciones editoriales con IA superó los $500 millones globales en 2025, con proyecciones de triplicarse en tres años según analistas del sector media y tecnología.","El modelo de negocio periodístico enfrenta una paradoja: la IA reduce costos pero puede acelerar la pérdida de suscriptores si el contenido pierde el diferencial humano que los lectores valoran."]},
  {"id":"politica","label":"Política","icon":"🏛️","tone":"Contextual","content":["Los marcos regulatorios de IA en periodismo avanzan a distintas velocidades: la UE lidera con el AI Act, mientras en América Latina cada medio decide sus propios estándares éticos de forma unilateral.","Los sindicatos de periodistas negocian cláusulas de IA en los convenios colectivos, exigiendo transparencia sobre qué contenidos son asistidos por algoritmos y cuáles son íntegramente humanos.","La concentración de mercado en pocas plataformas tecnológicas que controlan los modelos de IA plantea preguntas sobre dependencia e independencia editorial."]},
  {"id":"social","label":"Social","icon":"👥","tone":"Humano","content":["Periodistas freelance en Argentina y México reportan que las herramientas de IA les permiten competir con redacciones grandes, democratizando la producción de calidad antes reservada a grandes medios.","La desinformación generada por IA presenta un desafío sin precedentes: el deepfake de audio y video de figuras políticas ya influyó en coberturas electorales en tres países latinoamericanos.","Los lectores más jóvenes muestran mayor tolerancia al contenido asistido por IA que las generaciones anteriores, redefiniendo el contrato implícito entre periodista y audiencia."]},
  {"id":"internacional","label":"Internacional","icon":"🌍","tone":"Geopolítico","content":["El periodismo independiente en regímenes autoritarios encuentra en la IA un aliado: herramientas de síntesis y traducción permiten cubrir más temas con menos recursos humanos expuestos a riesgos.","Las grandes plataformas como Google y Meta usan IA para curar el feed informativo de miles de millones de usuarios, ejerciendo un poder editorial mayor que cualquier medio tradicional.","El acuerdo entre OpenAI y varios consorcios periodísticos para licenciar contenido marca un precedente en la disputa sobre derechos de autor en la era de los modelos de lenguaje."]},
  {"id":"cultural","label":"Cultural","icon":"🎭","tone":"Reflexivo","content":["La pregunta existencial del periodismo en la era de la IA no es tecnológica sino filosófica: ¿qué significa informar cuando una máquina puede sintetizar más datos que cualquier humano?","La autoridad periodística siempre se basó en la credibilidad construida con tiempo y error. Los algoritmos no tienen reputación que perder, lo que cambia radicalmente la ecuación de la confianza.","El periodismo de investigación —que requiere fuentes humanas, intuición y riesgo— puede ser el último reducto diferencial. Lo que no puede hacer una IA define el futuro de la profesión."]}
]'::jsonb
WHERE id = '4b8817b0-7adc-4a17-8d38-b60a114667d7';

UPDATE public.articles SET perspectives = '[
  {"id":"economica","label":"Económica","icon":"📈","tone":"Analítico","content":["La integración tecnológica regional en el Mercosur podría generar un mercado digital unificado de 300 millones de personas, el mayor de habla hispana y portuguesa del mundo.","Los costos de transacción entre los países miembro siguen siendo 3 veces más altos que en la UE, limitando el comercio electrónico transfronterizo que debería beneficiarse de la integración.","La propuesta de moneda digital común para pagos regionales enfrenta la resistencia de los bancos centrales, que ven en ella una amenaza a su soberanía monetaria."]},
  {"id":"politica","label":"Política","icon":"🏛️","tone":"Contextual","content":["La cumbre del Mercosur muestra la tensión entre dos modelos de integración: el político-progresista de Brasil y Argentina versus el comercial-pragmático de Uruguay y Paraguay.","La incorporación de Bolivia como miembro pleno y las negociaciones con Venezuela en suspenso revelan que la integración sigue siendo rehén de las alineaciones ideológicas de turno.","El acuerdo Mercosur-Unión Europea, negociado por 25 años, sigue sin ratificarse por resistencias ambientales europeas que el bloque sudamericano califica de proteccionismo encubierto."]},
  {"id":"social","label":"Social","icon":"👥","tone":"Humano","content":["La libre circulación de personas en el Mercosur beneficia a millones de migrantes regionales, pero las diferencias en reconocimiento de títulos profesionales siguen siendo un obstáculo cotidiano.","Los beneficios de la integración no llegan equitativamente: las ciudades fronterizas como Foz do Iguaçu o Ciudad del Este viven la integración de facto mientras las capitales negocian en abstracto.","Los jóvenes del Mercosur son los más integracionistas: encuestas muestran que el 70% de los menores de 30 apoyaría un pasaporte único regional."]},
  {"id":"internacional","label":"Internacional","icon":"🌍","tone":"Geopolítico","content":["El Mercosur negocia acuerdos simultáneos con China, India y los países del Golfo, buscando diversificar socios y reducir la dependencia histórica del eje atlántico.","Estados Unidos observa el acercamiento Mercosur-China con preocupación, presionando a sus socios para frenar inversiones en infraestructura digital de origen asiático.","La integración tecnológica regional es también una disputa por estándares: ¿se adoptará el modelo europeo de protección de datos o el modelo asiático de integración con el Estado?"]},
  {"id":"cultural","label":"Cultural","icon":"🎭","tone":"Reflexivo","content":["El Mercosur se pensó como integración económica pero produjo algo inesperado: una identidad cultural rioplatense compartida que trasciende las fronteras y se expresa en música, gastronomía y lenguaje.","La telenovela, el fútbol y el asado son la integración real del Mercosur. Los tratados comerciales se firman en cumbres; la integración cultural ocurre todos los días sin acuerdos formales.","La pregunta no es si el Mercosur sobrevivirá sino qué Mercosur queremos: ¿una zona de libre comercio o una comunidad de destino con identidad propia frente al mundo?"]}
]'::jsonb
WHERE id = '59e2e05f-f271-41e4-a133-67a6e025596f';

UPDATE public.articles SET perspectives = '[
  {"id":"economica","label":"Económica","icon":"📈","tone":"Analítico","content":["El ajuste en la tasa de interés y las nuevas restricciones cambiarias buscan frenar la salida de divisas y estabilizar el peso, a costa de enfriar la actividad económica y el consumo interno.","La inflación acumulada supera el 180% interanual, erosionando el poder adquisitivo de los salarios y complicando la planificación de cualquier empresa que opere en pesos.","Los acreedores internacionales monitorean las reservas brutas del Banco Central, que cayeron a niveles críticos, condicionando el acceso al crédito externo para refinanciar vencimientos."]},
  {"id":"politica","label":"Política","icon":"🏛️","tone":"Contextual","content":["La administración central recurre a recetas restrictivas que evidencian una falta de plan integral: cada medida de corto plazo genera un nuevo problema que requiere otra medida de emergencia.","La oposición fragmentada no logra articular una alternativa creíble, lo que paradójicamente da al gobierno margen para implementar ajustes que en otro contexto político serían inviables.","El FMI presiona por una convergencia al tipo de cambio único como condición para desembolsar los fondos del programa vigente, generando tensión con el ala política del gobierno."]},
  {"id":"social","label":"Social","icon":"👥","tone":"Humano","content":["Para el ciudadano común, estas decisiones técnicas se traducen rápidamente en un aumento del costo de vida: el precio del dólar en el mercado negro impacta en los bienes de consumo básicos al día siguiente.","Los trabajadores informales, que representan el 40% de la fuerza laboral, son los más vulnerables: no tienen protección de convenio colectivo y su poder adquisitivo se evapora con cada salto cambiario.","Las filas en los consulados de países europeos crecen cada vez que el dólar sube: la emigración no es solo económica sino una respuesta al agotamiento psicológico de vivir en crisis perpetua."]},
  {"id":"internacional","label":"Internacional","icon":"🌍","tone":"Geopolítico","content":["El FMI negocia en privado condiciones más duras de las que reconoce públicamente, generando incertidumbre sobre el verdadero estado de las finanzas públicas argentinas.","Los fondos de inversión internacionales que compraron deuda argentina a precio de default especulan con una eventual resolución favorable, manteniendo viva la posibilidad de un nuevo ciclo de endeudamiento.","La crisis argentina es observada como laboratorio de políticas monetarias extremas: sus resultados informarán las decisiones de otros países emergentes con problemas similares."]},
  {"id":"cultural","label":"Cultural","icon":"🎭","tone":"Reflexivo","content":["La crisis permanente moldeó un carácter nacional ambivalente: creatividad e ingenio para sobrevivir conviven con una fatiga colectiva que se manifiesta en cinismo, humor negro y planes de emigración.","El dólar no es solo una moneda en Argentina sino un termómetro cultural: su precio cotidiano estructura conversaciones, decisiones familiares y proyectos vitales de millones de personas.","La memoria de las crisis de 1989 y 2001 sigue viva en el ADN social: cada vez que el tipo de cambio se dispara, los argentinos activan protocolos de supervivencia aprendidos generacionalmente."]}
]'::jsonb
WHERE id = 'c2382c70-e553-4060-87ca-c996aef9f22c';
